name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master   # Or 'master', whichever branch you use

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Upload artifact (static files)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./snake_and_ladders_game   # Change if your site is inside a folder (e.g. ./public)

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
